apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: frontend
  labels:
    app: frontend
    app.kubernetes.io/managed-by: gcp-cloud-build-deploy
    backstage.io/kubernetes-id: backstage-component-id
  annotations:
    iam.gke.io/gcp-service-account: grafana@monitoring-scope-project-id.iam.gserviceaccount.com
