---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kpt-packages
  title: kpt-packages
  description: "Kpt Package for use in Kubernetes"
  tags:
    - bits
    - bits-tools
    - kubernetes
    - kpt
  annotations:
    github.com/project-slug: broadinstitute/kpt-packages
    backstage.io/techdocs-ref: dir:.
spec:
  type: library
  owner: devnull
  lifecycle: production
  