apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: grafana
  labels:
    app.kubernetes.io/managed-by: gcp-cloud-build-deploy
    backstage.io/kubernetes-id: backstage-component-id
    grafana_datasource: "1"
data:
  prometheus-datasource.yaml: |
    # Manage Data Sources via YAML Files
    # https://grafana.com/docs/grafana/latest/administration/provisioning/#data-sources
