apiVersion: v1
kind: ConfigMap
metadata:
  name: kptfile.kpt.dev
  annotations:
    config.kubernetes.io/local-config: "true"
  labels:
    backstage.io/kubernetes-id: atlantis
    app.kubernetes.io/managed-by: kpt
    environment: prod
data:
  name: atlantis
  namespace: atlantis
  cert-name: atlantis.example.com
