apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: http-to-https
  namespace: gcp-load-balancer
  labels:
    backstage.io/kubernetes-id: backstage-component-id
  annotations:
    internal.kpt.dev/upstream-identifier: 'networking.gke.io|FrontendConfig|default|http-to-https'
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
