apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: http-to-https
  namespace: gcp-load-balancer
  labels:
    app: gcp-load-balancer # kpt-set: ${name}
    backstage.io/kubernetes-id: backstage-component-id
spec:
  sslPolicy: gke-ingress-ssl-policy # kpt-set: ${sslPolicy}
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
