apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: name-example-managed-cert # kpt-set: ${name}-managed-cert
  namespace: gcp-load-balancer
  labels:
    backstage.io/kubernetes-id: backstage-component-id
    app.kubernetes.io/managed-by: gcp-cloud-build-deploy
    app: grafana
    name: label-example
  annotations:
    internal.kpt.dev/upstream-identifier: 'networking.gke.io|ManagedCertificate|default|name-example-managed-cert' # kpt-set: networking.gke.io|ManagedCertificate|default|${name}-managed-cert
spec:
  domains:
    - host.example.com # kpt-set: ${cert-name}
