apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /kptfile.kpt.dev
  name: kptfile.kpt.dev
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: v1|ConfigMap|default|kptfile.kpt.dev
  labels:
    app.kubernetes.io/managed-by: kpt
    backstage.io/kubernetes-id: gcp-load-balancer
    environment: prod
data:
  cert-name: cert.example.com
  name: gcp-load-balancer
  namespace: gcp-load-balancer
  sslPolicy: modern-tls12
