apiVersion: v1
kind: ConfigMap
metadata:
  name: kptfile.kpt.dev
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  name: atlantis
  namespace: atlantis
  atlantis-url: https://atlantis.example.com
  cert-name: atlantis.example.com
